"""Authoritative human-authored T13 calibration candidate definitions."""

from __future__ import annotations

from typing import Any

from ambiguity_manager.annotation.ids import format_record_id
from ambiguity_manager.annotation.schema import (
  ANNOTATION_SCHEMA_VERSION,
  HANDBOOK_VERSION,
  PACKAGE_VERSION,
)
def _base(
  index: int,
  *,
  command: str,
  scene_context: str | None,
  capability_context: str | None,
  dialogue_history: list[str],
  design_cell: dict[str, Any],
  seed_id: str,
  group_id: str,
  author_notes: str,
  provenance: str = "human_seed",
  template_id: str | None = None,
) -> dict[str, Any]:
  return {
    "record_id": format_record_id("calibration", index),
    "command": command,
    "dialogue_history": dialogue_history,
    "scene_context": scene_context,
    "capability_context": capability_context,
    "visible_provenance_category": provenance,
    "package_version": PACKAGE_VERSION,
    "handbook_version": HANDBOOK_VERSION,
    "annotation_schema_version": ANNOTATION_SCHEMA_VERSION,
    "dataset_partition": "calibration",
    "hidden": {
      "design_cell": design_cell,
      "seed_id": seed_id,
      "template_id": template_id or seed_id,
      "group_id": group_id,
      "author_notes": author_notes,
      "review_codes": ["naturalness_ok", "no_answer_leak"],
      "intended_answer": None,
      "model_output": None,
      "model_critique": None,
      "author_expectation": None,
    },
  }


def calibration_candidates() -> list[dict[str, Any]]:
  """Return exactly 24 reviewed calibration candidates."""
  records = [
    _base(
      1,
      command="Place the blue cup on the left coaster.",
      scene_context="Kitchen counter with one blue cup, one white cup, and two coasters labelled left and right.",
      capability_context="Mobile manipulator with gripper; can grasp cups and place on coasters.",
      dialogue_history=[],
      design_cell={
        "ambiguity_profile": "clear_no_ambiguity",
        "ambiguity_types": [],
        "compound_ambiguity_count": 0,
        "risk_level": "none",
        "capability_status": "capable",
        "recommended_strategy": "execute",
        "speech_act": "directive_command",
        "speech_act_proxy": "direct",
        "context_proxy": "context_rich",
        "safety_sensitive": False,
      },
      seed_id="cal-seed-01",
      group_id="cal-group-clear-01",
      author_notes="Clear direct execute case.",
    ),
    _base(
      2,
      command="Move that one over there.",
      scene_context="Workshop table with a small box and a large box; open shelf to the right.",
      capability_context="Mobile manipulator; can lift both boxes.",
      dialogue_history=["User: I need the shelf cleared a bit."],
      design_cell={
        "ambiguity_profile": "compound_two_types",
        "ambiguity_types": ["referential", "spatial"],
        "compound_ambiguity_count": 2,
        "risk_level": "low",
        "capability_status": "capable",
        "recommended_strategy": "clarify",
        "speech_act": "directive_command",
        "speech_act_proxy": "direct",
        "context_proxy": "context_rich",
        "safety_sensitive": False,
      },
      seed_id="cal-seed-02",
      group_id="cal-group-ref-spatial-01",
      author_notes="Referential + spatial compound; clarify.",
    ),
    _base(
      3,
      command="It's getting warm in here.",
      scene_context="Office with a closed window and a portable fan on the desk.",
      capability_context="Robot can open the window or switch on the fan.",
      dialogue_history=[],
      design_cell={
        "ambiguity_profile": "single_ambiguity",
        "ambiguity_types": ["pragmatic"],
        "compound_ambiguity_count": 1,
        "risk_level": "none",
        "capability_status": "capable",
        "recommended_strategy": "clarify",
        "speech_act": "indirect_request",
        "speech_act_proxy": "indirect",
        "context_proxy": "context_rich",
        "safety_sensitive": False,
      },
      seed_id="cal-seed-03",
      group_id="cal-group-pragmatic-01",
      author_notes="Indirect pragmatic request.",
    ),
    _base(
      4,
      command="Bring me some cups.",
      scene_context="Cupboard with six identical ceramic cups.",
      capability_context="Robot can carry up to three cups safely.",
      dialogue_history=["User: Guests are arriving soon."],
      design_cell={
        "ambiguity_profile": "single_ambiguity",
        "ambiguity_types": ["quantitative"],
        "compound_ambiguity_count": 1,
        "risk_level": "low",
        "capability_status": "conditional",
        "recommended_strategy": "clarify",
        "speech_act": "directive_command",
        "speech_act_proxy": "direct",
        "context_proxy": "context_rich",
        "safety_sensitive": False,
      },
      seed_id="cal-seed-04",
      group_id="cal-group-quant-01",
      author_notes="Quantitative ambiguity.",
    ),
    _base(
      5,
      command="Do it later.",
      scene_context="Robot is mid-task stacking clean plates beside a drying rack.",
      capability_context="Robot can pause and resume stacking.",
      dialogue_history=["Robot: Shall I finish stacking the plates now?"],
      design_cell={
        "ambiguity_profile": "single_ambiguity",
        "ambiguity_types": ["temporal"],
        "compound_ambiguity_count": 1,
        "risk_level": "none",
        "capability_status": "capable",
        "recommended_strategy": "clarify",
        "speech_act": "directive_command",
        "speech_act_proxy": "direct",
        "context_proxy": "context_rich",
        "safety_sensitive": False,
      },
      seed_id="cal-seed-05",
      group_id="cal-group-temporal-01",
      author_notes="Temporal underspecification.",
    ),
    _base(
      6,
      command="Use whichever mug you prefer for the tea.",
      scene_context="Two clean mugs on the counter; kettle is ready.",
      capability_context="Robot can pour tea into either mug.",
      dialogue_history=[],
      design_cell={
        "ambiguity_profile": "single_ambiguity",
        "ambiguity_types": ["preference"],
        "compound_ambiguity_count": 1,
        "risk_level": "none",
        "capability_status": "capable",
        "recommended_strategy": "silently_resolve",
        "speech_act": "directive_command",
        "speech_act_proxy": "direct",
        "context_proxy": "context_rich",
        "safety_sensitive": False,
      },
      seed_id="cal-seed-06",
      group_id="cal-group-pref-01",
      author_notes="Low-risk preference; silent resolve allowed.",
    ),
    _base(
      7,
      command="Put the leftovers away properly.",
      scene_context="Kitchen with an open container of cooked rice on the stove.",
      capability_context="Robot can move containers to fridge or cupboard.",
      dialogue_history=[],
      design_cell={
        "ambiguity_profile": "single_ambiguity",
        "ambiguity_types": ["commonsense"],
        "compound_ambiguity_count": 1,
        "risk_level": "low",
        "capability_status": "capable",
        "recommended_strategy": "clarify",
        "speech_act": "directive_command",
        "speech_act_proxy": "direct",
        "context_proxy": "minimal_context",
        "safety_sensitive": False,
      },
      seed_id="cal-seed-07",
      group_id="cal-group-commonsense-01",
      author_notes="Commonsense 'properly' underspecified.",
    ),
    _base(
      8,
      command="Pour a bit of that into the beaker.",
      scene_context="Lab bench with two unlabeled bottles beside a glass beaker.",
      capability_context="Robot can pour liquids; no chemical identification sensor.",
      dialogue_history=[],
      design_cell={
        "ambiguity_profile": "compound_two_types",
        "ambiguity_types": ["referential", "safety_precondition"],
        "compound_ambiguity_count": 2,
        "risk_level": "high",
        "capability_status": "unknown",
        "recommended_strategy": "clarify",
        "speech_act": "directive_command",
        "speech_act_proxy": "direct",
        "context_proxy": "context_rich",
        "safety_sensitive": True,
      },
      seed_id="cal-seed-08",
      group_id="cal-group-safety-01",
      author_notes="High-risk safety + referential; must clarify.",
    ),
    _base(
      9,
      command="Carry the sofa up the stairs.",
      scene_context="Living room with a three-seat sofa; staircase is narrow.",
      capability_context="Single mobile manipulator; maximum payload 8 kg; sofa mass approximately 40 kg.",
      dialogue_history=[],
      design_cell={
        "ambiguity_profile": "single_ambiguity",
        "ambiguity_types": ["capability"],
        "compound_ambiguity_count": 1,
        "risk_level": "medium",
        "capability_status": "incapable",
        "recommended_strategy": "face_preserving_rejection",
        "speech_act": "directive_command",
        "speech_act_proxy": "direct",
        "context_proxy": "context_rich",
        "safety_sensitive": True,
      },
      seed_id="cal-seed-09",
      group_id="cal-group-incapable-01",
      author_notes="Known incapable; reject.",
    ),
    _base(
      10,
      command="Do the usual setup.",
      scene_context=None,
      capability_context="Office assistant robot.",
      dialogue_history=["User: Same as Monday's meeting prep."],
      design_cell={
        "ambiguity_profile": "single_ambiguity",
        "ambiguity_types": ["contextual"],
        "compound_ambiguity_count": 1,
        "risk_level": "low",
        "capability_status": "unknown",
        "recommended_strategy": "clarify",
        "speech_act": "directive_command",
        "speech_act_proxy": "direct",
        "context_proxy": "minimal_context",
        "safety_sensitive": False,
      },
      seed_id="cal-seed-10",
      group_id="cal-group-contextual-01",
      author_notes="Contextual underspecification with thin scene.",
    ),
    _base(
      11,
      command="Where is the charger?",
      scene_context="Desk with a laptop; no charger visible.",
      capability_context="Robot has cameras and can report object locations.",
      dialogue_history=[],
      design_cell={
        "ambiguity_profile": "clear_no_ambiguity",
        "ambiguity_types": [],
        "compound_ambiguity_count": 0,
        "risk_level": "none",
        "capability_status": "capable",
        "recommended_strategy": "execute",
        "speech_act": "information_question",
        "speech_act_proxy": "direct",
        "context_proxy": "context_rich",
        "safety_sensitive": False,
      },
      seed_id="cal-seed-11",
      group_id="cal-group-infoq-01",
      author_notes="Information question; no action ambiguity.",
    ),
    _base(
      12,
      command="May I open the server cabinet?",
      scene_context="IT closet with a locked server cabinet.",
      capability_context="Robot can unlock cabinets only with authorised badge.",
      dialogue_history=[],
      design_cell={
        "ambiguity_profile": "clear_no_ambiguity",
        "ambiguity_types": [],
        "compound_ambiguity_count": 0,
        "risk_level": "medium",
        "capability_status": "conditional",
        "recommended_strategy": "clarify",
        "speech_act": "permission_request",
        "speech_act_proxy": "direct",
        "context_proxy": "context_rich",
        "safety_sensitive": True,
      },
      seed_id="cal-seed-12",
      group_id="cal-group-permission-01",
      author_notes="Permission request with policy sensitivity.",
    ),
    _base(
      13,
      command="Do not touch the hot plate.",
      scene_context="Kitchen with a glowing hot plate.",
      capability_context="Robot was approaching the stove area.",
      dialogue_history=[],
      design_cell={
        "ambiguity_profile": "clear_no_ambiguity",
        "ambiguity_types": [],
        "compound_ambiguity_count": 0,
        "risk_level": "high",
        "capability_status": "capable",
        "recommended_strategy": "execute",
        "speech_act": "prohibition",
        "speech_act_proxy": "direct",
        "context_proxy": "context_rich",
        "safety_sensitive": True,
      },
      seed_id="cal-seed-13",
      group_id="cal-group-prohibit-01",
      author_notes="Clear prohibition; comply/execute non-touch.",
    ),
    _base(
      14,
      command="If the cup is empty, refill it with water.",
      scene_context="Table with one ceramic cup; fill level not stated.",
      capability_context="Robot can pour water from a jug.",
      dialogue_history=[],
      design_cell={
        "ambiguity_profile": "single_ambiguity",
        "ambiguity_types": ["contextual"],
        "compound_ambiguity_count": 1,
        "risk_level": "none",
        "capability_status": "conditional",
        "recommended_strategy": "silently_resolve",
        "speech_act": "conditional_directive",
        "speech_act_proxy": "direct",
        "context_proxy": "minimal_context",
        "safety_sensitive": False,
      },
      seed_id="cal-seed-14",
      group_id="cal-group-conditional-01",
      author_notes="Conditional directive; may inspect then resolve.",
    ),
    _base(
      15,
      command="Tell me which box is lighter, then move that lighter box to the shelf.",
      scene_context="Two sealed boxes on the floor; open shelf ahead.",
      capability_context="Robot can weigh objects and move boxes under 5 kg.",
      dialogue_history=[],
      design_cell={
        "ambiguity_profile": "compound_two_types",
        "ambiguity_types": ["referential", "quantitative"],
        "compound_ambiguity_count": 2,
        "risk_level": "low",
        "capability_status": "capable",
        "recommended_strategy": "multi_step",
        "speech_act": "multi_intent",
        "speech_act_proxy": "direct",
        "context_proxy": "context_rich",
        "safety_sensitive": False,
      },
      seed_id="cal-seed-15",
      group_id="cal-group-multistep-01",
      author_notes="Multi-intent multi-step.",
    ),
    _base(
      16,
      command="Hello there.",
      scene_context="Lobby.",
      capability_context="Reception robot.",
      dialogue_history=[],
      design_cell={
        "ambiguity_profile": "clear_no_ambiguity",
        "ambiguity_types": [],
        "compound_ambiguity_count": 0,
        "risk_level": "none",
        "capability_status": "capable",
        "recommended_strategy": "execute",
        "speech_act": "other_non_actionable",
        "speech_act_proxy": "direct",
        "context_proxy": "minimal_context",
        "safety_sensitive": False,
      },
      seed_id="cal-seed-16",
      group_id="cal-group-nonaction-01",
      author_notes="Non-actionable greeting.",
    ),
    _base(
      17,
      command="Put it next to the other one after heating it for a while.",
      scene_context="Kitchen with two ceramic bowls and a microwave.",
      capability_context="Robot can operate microwave and place bowls.",
      dialogue_history=["User: The soup bowl still needs warming."],
      design_cell={
        "ambiguity_profile": "compound_three_or_more",
        "ambiguity_types": ["referential", "spatial", "temporal"],
        "compound_ambiguity_count": 3,
        "risk_level": "medium",
        "capability_status": "capable",
        "recommended_strategy": "multi_step",
        "speech_act": "directive_command",
        "speech_act_proxy": "direct",
        "context_proxy": "context_rich",
        "safety_sensitive": False,
      },
      seed_id="cal-seed-17",
      group_id="cal-group-compound3-01",
      author_notes="Three-type compound; multi-step clarify then act.",
    ),
    _base(
      18,
      command="Hand me the nearest tool.",
      scene_context="Workbench with a screwdriver and a hammer equally near the robot.",
      capability_context="Robot can hand tools to the user.",
      dialogue_history=[],
      design_cell={
        "ambiguity_profile": "compound_two_types",
        "ambiguity_types": ["referential", "preference"],
        "compound_ambiguity_count": 2,
        "risk_level": "low",
        "capability_status": "capable",
        "recommended_strategy": "clarify",
        "speech_act": "directive_command",
        "speech_act_proxy": "direct",
        "context_proxy": "context_rich",
        "safety_sensitive": False,
      },
      seed_id="cal-seed-18",
      group_id="cal-group-near-tie-01",
      author_notes="Nearest is tied; clarify.",
    ),
    _base(
      19,
      command="Slide the vase a little to the right.",
      scene_context="Shelf with one vase near the edge.",
      capability_context="Robot can translate objects by small offsets.",
      dialogue_history=[],
      design_cell={
        "ambiguity_profile": "single_ambiguity",
        "ambiguity_types": ["spatial"],
        "compound_ambiguity_count": 1,
        "risk_level": "medium",
        "capability_status": "capable",
        "recommended_strategy": "silently_resolve",
        "speech_act": "directive_command",
        "speech_act_proxy": "direct",
        "context_proxy": "context_rich",
        "safety_sensitive": False,
      },
      seed_id="cal-seed-19",
      group_id="cal-group-spatial-silent-01",
      author_notes="Fuzzy spatial with default small offset policy.",
    ),
    _base(
      20,
      command="Fly up and check the smoke alarm.",
      scene_context="Indoor corridor with a ceiling smoke alarm.",
      capability_context="Ground wheeled robot without flight capability.",
      dialogue_history=[],
      design_cell={
        "ambiguity_profile": "single_ambiguity",
        "ambiguity_types": ["capability"],
        "compound_ambiguity_count": 1,
        "risk_level": "medium",
        "capability_status": "incapable",
        "recommended_strategy": "face_preserving_rejection",
        "speech_act": "directive_command",
        "speech_act_proxy": "direct",
        "context_proxy": "context_rich",
        "safety_sensitive": True,
      },
      seed_id="cal-seed-20",
      group_id="cal-group-reject-flight-01",
      author_notes="Incapable flight request; reject.",
    ),
    _base(
      21,
      command="Could you pass the salt if there is any on the table?",
      scene_context="Dining table with pepper only; no salt visible.",
      capability_context="Robot can hand small objects.",
      dialogue_history=[],
      design_cell={
        "ambiguity_profile": "single_ambiguity",
        "ambiguity_types": ["pragmatic"],
        "compound_ambiguity_count": 1,
        "risk_level": "none",
        "capability_status": "conditional",
        "recommended_strategy": "execute",
        "speech_act": "indirect_request",
        "speech_act_proxy": "indirect",
        "context_proxy": "context_rich",
        "safety_sensitive": False,
      },
      seed_id="cal-seed-21",
      group_id="cal-group-indirect-cond-01",
      author_notes="Indirect conditional; execute report/no-op if absent.",
    ),
    _base(
      22,
      command="Clean that up somehow.",
      scene_context=None,
      capability_context="Cleaning robot with vacuum and wipe tools.",
      dialogue_history=["User: There was a spill earlier."],
      design_cell={
        "ambiguity_profile": "compound_three_or_more",
        "ambiguity_types": ["referential", "commonsense", "contextual"],
        "compound_ambiguity_count": 3,
        "risk_level": "unknown",
        "capability_status": "unknown",
        "recommended_strategy": "clarify",
        "speech_act": "directive_command",
        "speech_act_proxy": "direct",
        "context_proxy": "minimal_context",
        "safety_sensitive": False,
      },
      seed_id="cal-seed-22",
      group_id="cal-group-unknown-risk-01",
      author_notes="Unknown risk with compound underspecification.",
    ),
    _base(
      23,
      command="Move the sharp knife into the locked drawer.",
      scene_context="Counter with a chef's knife and a lockable drawer.",
      capability_context="Robot can grasp knives with caution protocol enabled.",
      dialogue_history=[],
      design_cell={
        "ambiguity_profile": "clear_no_ambiguity",
        "ambiguity_types": [],
        "compound_ambiguity_count": 0,
        "risk_level": "high",
        "capability_status": "capable",
        "recommended_strategy": "execute",
        "speech_act": "directive_command",
        "speech_act_proxy": "direct",
        "context_proxy": "context_rich",
        "safety_sensitive": True,
      },
      seed_id="cal-seed-23",
      group_id="cal-group-high-risk-clear-01",
      author_notes="High risk but clear and capable; execute carefully.",
    ),
    _base(
      24,
      command="After you identify which bottle is water, pour a little into the cup, then ask me before adding anything else.",
      scene_context="Table with three clear bottles and one empty cup.",
      capability_context="Robot has no reliable liquid classifier.",
      dialogue_history=[],
      design_cell={
        "ambiguity_profile": "compound_three_or_more",
        "ambiguity_types": ["referential", "safety_precondition", "quantitative"],
        "compound_ambiguity_count": 3,
        "risk_level": "high",
        "capability_status": "conditional",
        "recommended_strategy": "multi_step",
        "speech_act": "multi_intent",
        "speech_act_proxy": "direct",
        "context_proxy": "context_rich",
        "safety_sensitive": True,
      },
      seed_id="cal-seed-24",
      group_id="cal-group-safety-multistep-01",
      author_notes="Safety-sensitive multi-step; never silent high-risk resolve.",
    ),
  ]
  if len(records) != 24:
    raise RuntimeError(f"expected 24 calibration records, got {len(records)}")
  return records
